# (c) 2024 @Maxylan
version: '3.9'

networks:
  homienet:
    driver: bridge

volumes:
  homie.db_data:

services:
  homie.db: # Database
    image: mariadb:11.3-rc
    container_name: "${DB_HOST}"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${DB_PORT_FORWARDED}:${DB_PORT}"
    volumes:
      - './dockerfiles/dbdumps:/dbdumps'
      - './dockerfiles/init:/docker-entrypoint-initdb.d'
      - homie.db_data:/var/lib/mysql
    networks:
      - homienet

  homie.api: # Serves the Homie Backend API (Apache2 / httpd ?)
    image: # TBD
    container_name: "${API_HOST}"
    command: [ "/usr/sbin/apache2ctl", "-D", "FOREGROUND" ]
    restart: unless-stopped
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_URL: "${DB_HOST}:${DB_PORT}"
    ports:
      - "${API_PORT_FORWARDED}:${API_PORT}"
    volumes: 
      - './api:/var/www/html'
    networks:
      - homienet

  homie.httpd: # Serves Homie Frontend(s?) (Apache2 / httpd ?)
    image: # TBD
    container_name: "${HOMIE_HOST}"
    command: [ "/usr/sbin/apache2ctl", "-D", "FOREGROUND" ]
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      API_HOST: "${API_HOST}"
      API_PORT: "${API_PORT}"
      API_URL: "${API_HOST}:${API_PORT}"
    ports:
      - "${HOMIE_PORT_FORWARDED}:${HOMIE_PORT}"
    volumes: 
      - './frontend:/var/www/html'
    networks:
      - homienet
