# (c) 2024 @Maxylan
version: '3.9'

networks:
  homienet:
    driver: bridge

volumes:
  homie.db_data:

services:
  homie.db: # Database
    image: mariadb:11.3-rc
    container_name: "${DB_HOST}"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${DB_PORT_FORWARDED}:${DB_PORT}"
    volumes:
      - './dockerfiles/dbdumps:/dbdumps'
      - './dockerfiles/init:/docker-entrypoint-initdb.d'
      - homie.db_data:/var/lib/mysql
    networks:
      - homienet

# homie.api: # Homie Backend API
#   build: 
#     context: . 
#     dockerfile: ./dockerfiles/homie.api.Dockerfile # Scala (openjdk:11)
#   container_name: "${API_HOST}"
#   command: [ "sbt", "reStart" ]
#   restart: unless-stopped
#   environment:
#     DB_HOST: "${DB_HOST}"
#     DB_PORT: "${DB_PORT}"
#     DB_URL: "${DB_HOST}:${DB_PORT}"
#   ports:
#     - "${API_PORT_FORWARDED}:${API_PORT}"
#   volumes: 
#     - './src/api:/api'
#   networks:
#     - homienet

  homie.httpd: # Serves Homie Frontend(s?) (Apache2 / httpd ?)
    image: httpd:2.4
    container_name: "${HOMIE_HOST}"
    command: [ "/usr/sbin/apache2ctl", "-D", "FOREGROUND" ]
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      API_HOST: "${API_HOST}"
      API_PORT: "${API_PORT}"
      API_URL: "${API_HOST}:${API_PORT}"
    ports:
      - "${HOMIE_PORT_FORWARDED}:${HOMIE_PORT}"
    volumes: 
      - './src/app:/var/www/html'
    networks:
      - homienet

  homie.proxy: # Reverse Proxy, handles routing and stores logs, serving the entire application.
    build:
      context: . 
      dockerfile: ./dockerfiles/homie.proxy.Dockerfile # Scala (openjdk:11)
    container_name: "${HOST}"
    command: [ "sbt", "reStart" ]
    restart: unless-stopped
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_URL: "${DB_HOST}:${DB_PORT}"
      API_HOST: "${API_HOST}"
      API_PORT: "${API_PORT}"
      API_URL: "${API_HOST}:${API_PORT}"
      HOMIE_HOST: "${HOMIE_HOST}"
      HOMIE_PORT: "${HOMIE_PORT}"
      HOMIE_URL: "${HOMIE_HOST}:${HOMIE_PORT}"
    ports:
      - "${PORT_FORWARDED}:${PORT}"
      - "${SSL_PORT_FORWARDED}:${SSL_PORT}"
    volumes: 
      - './src/proxy:/proxy'
    networks:
      - homienet
